#!/bin/bash
#SBATCH --job-name=train
#SBATCH --output=./Exps/output.%A_%a.txt
#SBATCH --error=./Exps/error.%A_%a.txt
#SBATCH --nodes=1
#SBATCH --mem=80G
#SBATCH --exclude=gpu-06,gpu-05,gpu-01,gpu-51
#SBATCH --cpus-per-task=64
#SBATCH --gres=gpu:2
#SBATCH --partition=cscc-gpu-p
#SBATCH --time=24:00:00
#SBATCH --qos=cscc-gpu-qos

source /apps/local/anaconda3/conda_init.sh

conda activate envir

cd ~/two-TCP-Diffusion/

accelerate launch --config_file config.yaml --main_process_port 29501 train.py \
    --log "train" \
    --save "results/TCP_ICML_Test" \
